from selenium import webdriver

driver = webdriver.Chrome('C:\Personal\HTML-CSS\Python\chromedriver.exe')
driver.implicitly_wait(10)
driver.get('http://applabscloudnqa.bcg.com:42031/login')
assert ('DB Cargo Routing' in driver.title)
info = driver.find_element_by_class_name('info-text')
assert ('Bitte geben Sie Ihren 4-stelligen Pin ein' in info.text)
key1 = driver.find_element_by_id('db_input_login_one')
key1.send_keys('1')
key2 = driver.find_element_by_id('db_input_login_two')
key2.send_keys('2')
key3 = driver.find_element_by_id('db_input_login_three')
key3.send_keys('3')
key4 = driver.find_element_by_id('db_input_login_four')
key4.send_keys('4')
username = driver.find_element_by_id('db_text_user_name')
assert ('Hallo Daniel !' in username.text)
driver.close()
